version: '3.8'


services:
  db:
    image: postgres:14-alpine
    ports:
      - '5435:5432'  # Mapping container's port 5432 to the host's port 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=document_analyse

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db