# Generated by Django 5.0 on 2024-01-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='file_name', max_length=255),
            preserve_default=False,
        ),
    ]
